name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      - name: Deploy Docker container to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
            # Create the private key file
            echo "${PRIVATE_KEY}" > private_key.pem
            chmod 600 private_key.pem

            # Add the server to known hosts (to avoid host key verification errors)
            ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

            # SSH into the server and deploy the container
            ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << EOF
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/my-app:latest
            EOF


